[[questions]]
question = """「REVOKE」コマンドの説明として正しいものは次のうちどれか?
[1] データベースのユーザに権限を付与する
[2] データベースのユーザから権限を削除する
[3] ユーザーの認証情報を削除する
[4] ユーザーのパスワードを変更する"""
answer = 2

[[questions]]
question = """\"""pg_stat_activity\"""ビューについて正しいものはどれか?
[1] 各ユーザがアクセスしたテーブルの統計情報を表示する
[2] 現在接続中の各セッションのアクティビティ情報を提供する
[3] 各テーブルのサイズと、過去のGROWTHの情報を表示する
[4] データベース内のすべてのテーブルのロック情報を提供する"""
answer = 2

[[questions]]
question = """ロールに対して「CREATEDB」権限を設定するとどのような挙動となるか?
[1] ロールが新たにデータベースを作成することが許可される
[2] ロールが新たにテーブルを作成することが許可される
[3] ロールが新たにユーザを作成することが許可される
[4] ロールが新たに角ou'relを作成することが許可される"""
answer = 1

[[questions]]
question = """'EXPLAIN ANALYZE' コマンドの使用目的として適切なものはどれか?
[1] クエリがどのように実行されるかを確認するため
[2] データベースのリカバリータイムを確認するため
[3] データベースの構成を確認するため
[4] データベースのバージョンを確認するため"""
answer = 1

[[questions]]
question = """PostgreSQLで「VACUUM」コマンドを実行する主な目的は何か?
[1] データベースを最適化する
[2] データベースのサイズを減らす
[3] データベースをクリーンアップし、使用されないディスクスペースを解放する
[4] 不要なデータを削除する"""
answer = 3

[[questions]]
question = """「pg_dumpall」コマンドが出力するバックアップの特徴として適切なものは何か？
[1] パーティショニング構造を含むデータベース全体のバックアップを作成する
[2] データベースの一部だけをバックアップする
[3] インデックスのみをバックアップする
[4] データベースのスキーマをバックアップしない"""
answer = 1

[[questions]]
question = """PostgreSQLにおける「WAL」の説明として最も正しいものは何か？
[1] Write Ahead Logの略で、変更内容を記録し、クラッシュ回復に使用する
[2] Write All Logの略で、すべてのトランザクションを記録する
[3] Write Activity Logの略で、ユーザーの行動を記録する
[4] Write Access Logの略で、全てのアクセスを記録する"""
answer = 1

[[questions]]
question = """「SELECT FOR UPDATE」クエリの使用目的として正しいものはどれか?
[1] テーブルをロックして更新する準備をする
[2] データベースの一貫性を確保する
[3] 問い合わせ高速化のため
[4] テーブルのサイズを取得する"""
answer = 1

[[questions]]
question = """pg_dumpでダンプしたデータを元に戻す際に用いるツールは何か？
[1] psql
[2] pg_restore
[3] pg_dumpall
[4] SQL"""
answer = 2

[[questions]]
question = """'pg_stat_activity'テーブルについて、正しく説明したものは次のうちどれか？
[1] データベース内のすべてのテーブルのロック情報を表示する
[2] データベース内のすべてのテーブルのアクセス統計情報を表示する
[3] データベースの各テーブルごとに1行の形で、テーブルへのアクセス率を表示する
[4] 現在接続中のすべてのバックエンドに関する情報を表示する"""
answer = 4

[[questions]]
question = """'EXPLAIN'コマンドについて、正しく説明したものは次のうちどれか？
[1] クエリを実行し、その結果を表示する
[2] クエリが利用するインデックスを表示する
[3] クエリの実行計画を表示する
[4] クエリが何をするかを詳細に表示する"""
answer = 3

[[questions]]
question = """'ANALYZE'コマンドについて、正しく説明したものは次のうちどれか？
[1] クエリの実行計画を分析し、最適化する
[2] テーブルの統計データを集計し、クエリが利用できるようにする
[3] テーブルのデータ不整合を分析し、解消する
[4] テーブルのデータを分析し、その結果を報告する"""
answer = 2

[[questions]]
question = """'VACUUM FULL'コマンドが何を行うか正しく説明したものは次のうちどれか？
[1] データベース全体のディスクを解放し、テーブル空間を最小化する
[2] データベース全体のインデックスを再作成する
[3] データベース全体のテーブルを解析し、統計情報を更新する
[4] データベース全体のテーブルをロックし、他の操作をブロックする"""
answer = 1

[[questions]]
question = """データベーススナップショットを作成するために、PostgreSQLでは何を使用するのか？
[1] pg_dump
[2] pg_snapshot
[3] pg_copy
[4] pg_backup"""
answer = 1

[[questions]]
question = """次のうち、PostgreSQLの「pg_dump」コマンドがバックアップを作成する際にどの形式を使用するか？
[1] SQL形式
[2] 二進形式
[3] 圧縮形式
[4] カスタム形式"""
answer = 4

[[questions]]
question = """PostgreSQLで、トランザクション内で発生した全ての変更を元に戻すSQLコマンドは何か？
[1] ROLLBACK
[2] COMMIT
[3] UNDO
[4] REDO"""
answer = 1

[[questions]]
question = """'ENABLE_SEQSCAN'設定パラメータが何を制御するか正しく説明したものは次のうちどれか？
[1] シーケンシャルスキャンの有効化/無効化を制御する
[2] クエリオプティマイザがシーケンスジェネレータを使用するかどうかを制御する
[3] シーケンスの自動バキュームを制御する
[4] シーケンスの値を自動的にリセットする"""
answer = 1

[[questions]]
question = """'pg_cancel_backend(pid)'関数がどのような役割を果たすか正しく説明したものは次のうちどれか？
[1] 特定のバックエンドプロセスをキャンセルする
[2] 特定のバックエンドプロセスを強制終了する
[3] 特定のバックエンドプロセスの優先度を変更する
[4] 特定のバックエンドプロセスのセッションを終了する"""
answer = 1

[[questions]]
question = """次のうち、論理レプリケーションで同期されるものは何か？
[1] データベース全体
[2] テーブル
[3] スキーマ
[4] ロール"""
answer = 2

[[questions]]
question = """'pg_stat_user_tables'ビューが提供する情報は何か？
[1] ユーザーが定義したテーブルのアクセス統計
[2] ユーザーが定義したテーブルのサイズ
[3] ユーザーが定義したテーブルのスキーマ情報
[4] ユーザーが定義したテーブルの権限情報"""
answer = 1

[[questions]]
question = """次のうち、'pg_stat_replication'ビューに関する正しい説明は何か？\
[1] レプリケーションの進捗を表示する\
[2] レプリケーションの設定を表示する\
[3] レプリケーションのエラーログを表示する\
[4] レプリケーションスロットの状況を表示する"""
answer = 1

[[questions]]
question = """'pg_is_in_recovery()'関数の戻り値が 'true' の場合、その意味はどれか？\
[1] データベースがリカバリモード中である\
[2] データベースのリカバリが完了した\
[3] データベースのリカバリが正常に行われている\
[4] データベースサーバがリカバリ中に問題が発生した"""
answer = 1

[[questions]]
question = """次のうち、PostgreSQLのパラメータ'work_mem'が制御するものは何か？\
[1] ディスクI/Oの量\
[2] ソートやハッシュ操作で使用するメモリの量\
[3] 共有バッファのサイズ\
[4] 自動バキュームワーカーの数"""
answer = 2

[[questions]]
question = """WALレコードを生成せずに読み取り専用のトランザクションを開始するための設定は何か？\
[1] SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\
[2] SET TRANSACTION READ ONLY;\
[3] SET TRANSACTION ISOLATION LEVEL READ COMMITTED;\
[4] SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;"""
answer = 2

[[questions]]
question = """pg_stat_activityテーブルが現在の接続セッションに関する情報を提供するとき、特定の接続がどのような状態にあるかを示す項目は何か？\
[1] state\
[2] query\
[3] datname\
[4] usename"""
answer = 1

[[questions]]
question = """WALレコードを保存する場所を指定する設定パラメータは何か？\
[1] wal_directory\
[2] data_directory\
[3] log_directory\
[4] pgdata"""
answer = 1

[[questions]]
question = """トランザクションが終了したあともロックを維持することが可能なロックの種類は何か？\
[1] 共有ロック\
[2] 排他ロック\
[3] 明示的ロック\
[4] アドバイザリロック"""
answer = 4

[[questions]]
question = """psqlコマンドラインツールで使用する独自のSQLコマンドが前に'\\'を必要とすることから、これらのコマンドは何と呼ばれるか？\
[1] スラッシュコマンド\
[2] バックスラッシュコマンド\
[3] ダッシュコマンド\
[4] アンダースコアコマンド"""
answer = 2

[[questions]]
question = """SELECT文にFOR UPDATEを使用すると、どのようなロックが発生するか？\
[1] 共有ロック\
[2] 排他ロック\
[3] 共有アクセス排他制御ロック\
[4] 行レベルロック"""
answer = 2

[[questions]]
question = """pg_hba.confファイルが制御する内容は何か？\
[1] クエリの実行計画\
[2] クライアントの接続制御\
[3] バックアップスケジュール\
[4] テーブルの分散制御"""
answer = 2

[[questions]]
question = """PostgreSQLでバックアップとリストアを行うためのユーティリティは何か？\
[1] pg_backup\
[2] pg_restore\
[3] pg_dump\
[4] pg_archiver"""
answer = 3

[[questions]]
question = """PostgreSQLの「テーブルスペース」の役割は何か？\
[1] ディスクの物理的な位置を管理する\
[2] データベースの論理的な分割を管理する\
[3] データベースのテーブルの物理的な分割を管理する\
[4] データベースの各テーブルのデータとインデックスを管理する"""
answer = 1

[[questions]]
question = """リプリケーションスロットの主な目的は何か？\
[1] レプリケーションのパフォーマンスを向上するため\
[2] マスターノードとスタンバイノード間のレプリケーションを同期するため\
[3] スタンバイが接続していない間も必要なWALファイルがマスターで保持されるようにするため\
[4] レプリケーションに使用するネットワークリソースを制限するため"""
answer = 3

[[questions]]
question = """PostgreSQLで行単位のセキュリティを実現するためには何を使用するべきか？\
[1] ユーザーロール\
[2] 外部認証ツール\
[3] ロールレベルセキュリティ（RLS）\
[4] データベースファイアウォール"""
answer = 3

[[questions]]
question = """PostgreSQLの\"""shared_buffers\"""設定は何に影響を与えるか？\
[1] システムがデータベースのキャッシュに確保できるメモリの量\
[2] 同時に開けるファイルの最大数\
[3] 同時に実行できるクエリの数\
[4] 同時に接続できるクライアントの数"""
answer = 1

[[questions]]
question = """最初のトランザクションが行を排他的にロックしているとき、PostgreSQLが二番目のトランザクションに同じ行へのアクセスを試みるとどのような結果になるか？\
[1] 二番目のトランザクションはすぐにエラーを返す\
[2] 二番目のトランザクションは最初のトランザクションがコミットまたはロールバックするまで待機\
[3] 二番目のトランザクションは最初のトランザクションがロックを解除するまで待機\
[4] 二番目のトランザクションは行を読むための共有ロックを獲得"""
answer = 2

[[questions]]
question = """pg_dumpコマンドを実行した時のデフォルト出力形式は何か？\
[1] プレーンテキスト\
[2] カスタム形式\
[3] ディレクトリ形式\
[4] 圧縮形式"""
answer = 1

[[questions]]
question = """PostgreSQLでテーブルの外部参照整合性を強制するためには何を使用するべきか？\
[1] 外部キー制約\
[2] ユニーク制約\
[3] チェック制約\
[4] プライマリーキー制約"""
answer = 1

[[questions]]
question = """PostgreSQLで、データベースとOSの時間帯が異なるときに使用する設定項目は何か？\
[1] timezone\
[2] datestyle\
[3] lc_time\
[4] intervalstyle"""
answer = 1

[[questions]]
question = """pg_basebackupコマンドを用いて取得するバックアップの種類は何か？\
[1] フルバックアップ\
[2] 差分バックアップ\
[3] 増分バックアップ\
[4] デルタバックアップ"""
answer = 1

[[questions]]
question = """pg_stat_statementsモジュールが提供する情報は何か？\
[1] SQL文の実行統計\
[2] テーブルのアクセス統計\
[3] データベースの接続統計\
[4] ユーザーの活動統計"""
answer = 1

[[questions]]
question = """一つのクエリが多数のインデックスページやテーブルページを読み込むときに有用な設定は何か？\
[1] work_memの増加\
[2] shared_buffersの増加\
[3] effective_cache_sizeの増加\
[4] maintenance_work_memの増加"""
answer = 3

[[questions]]
question = """COPYコマンドで読み込めるデータフォーマットは何か？\
[1] CSVのみ\
[2] バイナリのみ\
[3] CSVとテキスト\
[4] CSVとバイナリ"""
answer = 4

[[questions]]
question = """PostgreSQLがデータベースを自動的にクリーンアップするメカニズムは何か？\
[1] VACUUM\
[2] AUTOCLEAN\
[3] AUTOVACUUM\
[4] CLEANUP"""
answer = 3

[[questions]]
question = """PostgreSQLのテーブルで特に大きなデータ型を保存するための方法は何か？\
[1] Text型のカラムを使用する\
[2] Bytea型のカラムを使用する\
[3] 外部テーブルを使用する\
[4] Large Objectを使用する"""
answer = 4

[[questions]]
question = """PostgreSQLで異なるトランザクション内でそれぞれの状態を独立させるために用いる方法は何か？\
[1] トランザクション分離レベルを設定する\
[2] トランザクションを同時実行する\
[3] トランザクションを順序付ける\
[4] トランザクションをグループ化する"""
answer = 1

[[questions]]
question = """PostgreSQLのUNLOGGEDテーブルの特徴として正しいものは何か？\
[1] 書き込み速度が速く、クラッシュリカバリやレプリケーションのログを必要としない\
[2] 読み取り速度が速く、クラッシュリカバリやレプリケーションのログを必要としない\
[3] 書き込み速度が速く、クラッシュリカバリをサポートする\
[4] 読み取り速度が速く、クラッシュリカバリをサポートする"""
answer = 1

[[questions]]
question = """PostgreSQLのランダムアクセスパフォーマンスを向上させるための設定は何か？\
[1] shared_buffersを増やす\
[2] work_memを増やす\
[3] effective_cache_sizeを増やす\
[4] max_connectionsを増やす"""
answer = 1

[[questions]]
question = """PostgreSQLで、バックアップを取るために用いられる、データベース全体をファイルシステムのレベルでバックアップする方法は何か？\
[1] ファイルシステムレベルバックアップ\
[2] 完全バックアップ\
[3] データベースレベルバックアップ\
[4] 物理バックアップ"""
answer = 1

[[questions]]
question = """PostgreSQLでトランザクション終了後もリソースのロックを維持する方法は何か？\
[1] 共有ロック\
[2] 排他ロック\
[3] アドバイザリロック\
[4] 明示的ロック"""
answer = 3

[[questions]]
question = """PostgreSQLで、システムがアクセスするテーブルのデータをインメモリにキャッシュするバッファエリアのサイズを制御する設定パラメータは何か？\
[1] work_mem\
[2] shared_buffers\
[3] effective_cache_size\
[4] maintenance_work_mem"""
answer = 2

[[questions]]
question = """PostgreSQLの「EXPLAIN」コマンドは、以下のどれについて情報を提供するか？\
[1] SQLクエリの実行計画\
[2] SQLクエリが返す結果セット\
[3] SQLクエリが生成するログの内容\
[4] SQLクエリが必要とする所定の権限"""
answer = 1

[[questions]]
question = """PostgreSQLの「ANALYZE」コマンドが何を行うか正しく説明したものは次のうちどれか？\
[1] テーブルの統計データを収集し、クエリプランナが利用できるようにする\
[2] クエリの実行計画を分析し、最適化する\
[3] テーブルのデータ不整合を分析し、解消する\
[4] テーブルスペースを分析し、その結果を報告する"""
answer = 1

[[questions]]
question = """PostgreSQLでクエリの性能を向上させるための最適化パラメータとして、最もよく使われるパラメータは何か？\
[1] work_mem\
[2] shared_buffers\
[3] maintenance_work_mem\
[4] effective_io_concurrency"""
answer = 1

[[questions]]
question = """PostgreSQLで同時実行トランザクションの挙動を制御するための若干途中急ぎ参加先は何か？\
[1] isolation_level\
[2] transaction_isolation\
[3] concurrent_transactions\
[4] transaction_control"""
answer = 2

[[questions]]
question = """PostgreSQLでアクティブなトランザクションのリストを確認するためのコマンドは何か？\
[1] SHOW TRANSACTIONS;\
[2] SELECT * FROM pg_stat_activity;\
[3] SELECT * FROM pg_transactions;\
[4] pg_dumpall -l"""
answer = 2

